### GET REQUEST
GET http://localhost:8080/1680115106204


### POST REQUEST
POST http://localhost:8080/1680114809399
content-type: application/json

{"test":"xxxxxxxxxxxxxxxxxxxxxxxxx"}


### PUT REQUEST
PUT http://localhost:8080/1680114898672
content-type: application/json

{
	"hello":{"new pepper test 2"}
}

### DELETE REQUEST
DELETE http://localhost:8080