### GET REQUEST
GET http://localhost:8080/1679949082030/users


### POST REQUEST
POST http://localhost:8080/
content-type: application/json

{"test":"xxxxxxxxxxxxxxxxxxxxxxxxx"}


### PUT REQUEST
PUT http://localhost:8080/1680114805517/users/2
content-type: application/json

 {"firstName":"Parker", "lastName":"Keller"}


### DELETE REQUEST
DELETE http://localhost:8080/